### ISSUE TITLE
Basic Admin Components

### ISSUE THREAD

**Issue by ngpeijiun** [ngpeijiun/boss-admin#4]
The objective is to be able to define something like below:

```javascript
<BossApp>
    <BossHeader>
        <BossIcon><li className="fa fa-bars"></li></BossIcon>
    </BossHeader>
    <BossBody>
        <BossNav></BossNav>
    </BossBody>
</BossApp>
```

And produce something like below:

> ![image](https://user-images.githubusercontent.com/11265027/89719697-9bad4a80-d9fd-11ea-9425-82fca0371d6b.png)

List of components required:

1. `BossApp`
2. `BossHeader`
3. `BossBody`
4. `BossNav`
5. `BossIcon`

Suggested CSS style:

```css
* {
    box-sizing: border-box;
}

div {
    display: flex;
}

.BossApp {
    flex-direction: column;
    height: 100vh;
    width: 100vw;
}

.BossHeader {
    align-items: center;
    background-color: #000;
    color: #ddd;
    border-bottom: 1px solid #333;
    height: 1.2cm;
    padding: 0.1cm;
    width: 100vw;
}

.BossBody {
    flex: 1 1 auto;
}

.BossNav {
    background-color: #000;
    height: 100%;
    width: 6cm;
}

.BossIcon {
    align-items: center;
    cursor: pointer;
    font-size: 0.4cm;
    justify-content: center;
    min-height: 1cm;
    min-width: 1cm;
}

```
